# Working with Text Data

In [1]:
import pandas as pd

## This Module's Dataset
- This module's dataset (`chicago.csv`) is a collection of public sector employees in the city of Chicago.
- Each row includes the employee's name, position, department, and salary.

In [ ]:
chicago = pd.read_csv("chicago.csv").dropna(how="all").astype({"Department":"category"})

chicago.head()

,Name,Position Title,Department,Employee Annual Salary
0,"AARON, ELVIA J",WATER RATE TAKER,WATER MGMNT,$90744.00
1,"AARON, JEFFERY M",POLICE OFFICER,POLICE,$84450.00
2,"AARON, KARINA",POLICE OFFICER,POLICE,$84450.00
3,"AARON, KIMBERLEI R",CHIEF CONTRACT EXPEDITER,GENERAL SERVICES,$89880.00
4,"ABAD JR, VICENTE M",CIVIL ENGINEER IV,WATER MGMNT,$106836.00

In [10]:
chicago.info()

<class 'pandas.Series'>
RangeIndex: 32062 entries, 0 to 32061
Series name: Department
Non-Null Count  Dtype
--------------  -----
32062 non-null  category
dtypes: category(1)
memory usage: 31.7 KB

In [13]:
chicago.nunique()

Name                      31776
Position Title             1093
Department                   35
Employee Annual Salary     1156
dtype: int64

## Common String Methods
- A `Series` has a special `str` attribute that exposes an object with string methods.
- Access the `str` attribute, then invoke the string method on the nested object.
- Most method names will match their Python method equivalents (`upper`, `lower`, `title`, etc).

In [16]:
chicago = pd.read_csv("chicago.csv").dropna(how="all").astype({"Department":"category"})

chicago.head()

,Name,Position Title,Department,Employee Annual Salary
0,"AARON, ELVIA J",WATER RATE TAKER,WATER MGMNT,$90744.00
1,"AARON, JEFFERY M",POLICE OFFICER,POLICE,$84450.00
2,"AARON, KARINA",POLICE OFFICER,POLICE,$84450.00
3,"AARON, KIMBERLEI R",CHIEF CONTRACT EXPEDITER,GENERAL SERVICES,$89880.00
4,"ABAD JR, VICENTE M",CIVIL ENGINEER IV,WATER MGMNT,$106836.00

In [26]:
chicago["Position Title"].str.lower()
chicago["Position Title"].str.upper()
chicago["Position Title"].str.title()
chicago["Position Title"].str.len()
chicago["Position Title"].str.strip()
chicago["Position Title"].str.lstrip()
chicago["Position Title"].str.count("A")

chicago["Department"].str.replace("MGMNT", "MANAGEMENT").str.title()

0        Water Management
1                  Police
2                  Police
3        General Services
4        Water Management
               ...
32057    General Services
32058              Police
32059              Police
32060              Police
32061                Doit
Name: Department, Length: 32062, dtype: str

- The `str` attribute exposes an object that supports square bracket syntax for indexing.
- You can provide values, slices, or negative numbers.

In [ ]:
chicago["Department"].str[0]
chicago["Department"].str[3]
chicago["Department"].str[1:7]
chicago["Department"].str[0:7]

0        WATER M
1         POLICE
2         POLICE
3        GENERAL
4        WATER M
          ...
32057    GENERAL
32058     POLICE
32059     POLICE
32060     POLICE
32061       DoIT
Name: Department, Length: 32062, dtype: object

## Filtering with String Methods
- The `str.contains` method checks whether a substring exists anywhere in the string.
- The `str.startswith` method checks whether a substring exists at the start of the string.
- The `str.endswith` method checks whether a substring exists at the end of the string.

In [31]:
chicago = pd.read_csv("chicago.csv").dropna(how="all").astype({"Department":"category"})

chicago.head()

,Name,Position Title,Department,Employee Annual Salary
0,"AARON, ELVIA J",WATER RATE TAKER,WATER MGMNT,$90744.00
1,"AARON, JEFFERY M",POLICE OFFICER,POLICE,$84450.00
2,"AARON, KARINA",POLICE OFFICER,POLICE,$84450.00
3,"AARON, KIMBERLEI R",CHIEF CONTRACT EXPEDITER,GENERAL SERVICES,$89880.00
4,"ABAD JR, VICENTE M",CIVIL ENGINEER IV,WATER MGMNT,$106836.00

In [36]:
water_workers = chicago["Position Title"].str.lower().str.contains("water")
water_workers = chicago["Position Title"].str.contains("water", case=False)

chicago[water_workers]

,Name,Position Title,Department,Employee Annual Salary
0,"AARON, ELVIA J",WATER RATE TAKER,WATER MGMNT,$90744.00
554,"ALUISE, VINCENT G",FOREMAN OF WATER PIPE CONSTRUCTION,WATER MGMNT,$102440.00
671,"ANDER, PERRY A",WATER CHEMIST II,WATER MGMNT,$82044.00
685,"ANDERSON, ANDREW J",DISTRICT SUPERINTENDENT OF WATER DISTRIBUTION,WATER MGMNT,$109272.00
702,"ANDERSON, DONALD",FOREMAN OF WATER PIPE CONSTRUCTION,WATER MGMNT,$102440.00
...,...,...,...,...
29669,"VERMA, ANUPAM",MANAGING ENGINEER - WATER MANAGEMENT,WATER MGMNT,$111192.00
30239,"WASHINGTON, JOSEPH",WATER CHEMIST III,WATER MGMNT,$89676.00
30544,"WEST, THOMAS R",GEN SUPT OF WATER MANAGEMENT,WATER MGMNT,$115704.00
30991,"WILLIAMS, MATTHEW",FOREMAN OF WATER PIPE CONSTRUCTION,WATER MGMNT,$102440.00
31405,"WOODRIDGE, ROBERT L",FOREMAN OF WATER PIPE CONSTRUCTION,WATER MGMNT,$102440.00

In [37]:
chicago["Position Title"].str.lower().str.startswith("civil")

0        False
1        False
2        False
3        False
4         True
         ...
32057    False
32058    False
32059    False
32060    False
32061    False
Name: Position Title, Length: 32062, dtype: bool

## String Methods on Index and Columns
- Use the `index` and `columns` attributes to access the `DataFrame` index/column labels.
- These objects support string methods via their own `str` attribute.

In [38]:
chicago = pd.read_csv("chicago.csv", index_col="Name").dropna(how="all").astype({"Department":"category"})

chicago.head()

,Position Title,Department,Employee Annual Salary
Name,,,
"AARON, ELVIA J",WATER RATE TAKER,WATER MGMNT,$90744.00
"AARON, JEFFERY M",POLICE OFFICER,POLICE,$84450.00
"AARON, KARINA",POLICE OFFICER,POLICE,$84450.00
"AARON, KIMBERLEI R",CHIEF CONTRACT EXPEDITER,GENERAL SERVICES,$89880.00
"ABAD JR, VICENTE M",CIVIL ENGINEER IV,WATER MGMNT,$106836.00

In [42]:
chicago.index = chicago.index.str.strip().str.title()

In [43]:
chicago.head()

,Position Title,Department,Employee Annual Salary
Name,,,
"Aaron, Elvia J",WATER RATE TAKER,WATER MGMNT,$90744.00
"Aaron, Jeffery M",POLICE OFFICER,POLICE,$84450.00
"Aaron, Karina",POLICE OFFICER,POLICE,$84450.00
"Aaron, Kimberlei R",CHIEF CONTRACT EXPEDITER,GENERAL SERVICES,$89880.00
"Abad Jr, Vicente M",CIVIL ENGINEER IV,WATER MGMNT,$106836.00

In [46]:
chicago.columns = chicago.columns.str.upper()

## The str.split Method
- The `str.split` method splits a string by the occurrence of a delimiter. Pandas returns a `Series` of lists.
- Use the `str.get` method to access a nested list element by its index position.

In [47]:
chicago = pd.read_csv("chicago.csv").dropna(how="all").astype({"Department":"category"})

chicago.head()

,Name,Position Title,Department,Employee Annual Salary
0,"AARON, ELVIA J",WATER RATE TAKER,WATER MGMNT,$90744.00
1,"AARON, JEFFERY M",POLICE OFFICER,POLICE,$84450.00
2,"AARON, KARINA",POLICE OFFICER,POLICE,$84450.00
3,"AARON, KIMBERLEI R",CHIEF CONTRACT EXPEDITER,GENERAL SERVICES,$89880.00
4,"ABAD JR, VICENTE M",CIVIL ENGINEER IV,WATER MGMNT,$106836.00

In [48]:
chicago["Position Title"].str.split(" ")

0                        [WATER, RATE, TAKER]
1                           [POLICE, OFFICER]
2                           [POLICE, OFFICER]
3                [CHIEF, CONTRACT, EXPEDITER]
4                       [CIVIL, ENGINEER, IV]
                         ...
32057    [FRM, OF, MACHINISTS, -, AUTOMOTIVE]
32058                       [POLICE, OFFICER]
32059                       [POLICE, OFFICER]
32060                       [POLICE, OFFICER]
32061            [CHIEF, DATA, BASE, ANALYST]
Name: Position Title, Length: 32062, dtype: object

- Let's find the most common first name among the employees.

In [54]:
chicago["Name"].str.title().str.split(", ").str.get(1).str.strip().str.split(" ").str.get(0).value_counts()

Name
Michael    1153
John        899
James       676
Robert      622
Joseph      537
           ...
Sandino       1
Hamzeh        1
Janaan        1
Alen          1
Mac           1
Name: count, Length: 5091, dtype: int64

## The expand and n Parameters of the str.split Method
- The `expand` parameter returns a `DataFrame` instead of a `Series` of lists.
- The `n` parameter limits the number of splits.

In [55]:
chicago = pd.read_csv("chicago.csv").dropna(how="all").astype({"Department":"category"})

chicago.head()

,Name,Position Title,Department,Employee Annual Salary
0,"AARON, ELVIA J",WATER RATE TAKER,WATER MGMNT,$90744.00
1,"AARON, JEFFERY M",POLICE OFFICER,POLICE,$84450.00
2,"AARON, KARINA",POLICE OFFICER,POLICE,$84450.00
3,"AARON, KIMBERLEI R",CHIEF CONTRACT EXPEDITER,GENERAL SERVICES,$89880.00
4,"ABAD JR, VICENTE M",CIVIL ENGINEER IV,WATER MGMNT,$106836.00

               0             1
0          Aaron       Elvia J
1          Aaron     Jeffery M
2          Aaron        Karina
3          Aaron   Kimberlei R
4        Abad Jr     Vicente M
...          ...           ...
32057    Zygadlo     Michael J
32058   Zygowicz       Peter J
32059   Zymantas        Mark E
32060  Zyrkowski       Carlo E
32061  Zyskowski       Dariusz

[32062 rows x 2 columns]

## The explode Method
- The `explode` method transforms a `Series` of lists into a column with a separate row for each list element.
- Pandas preserves the original index. Use `reset_index` with `drop=True` to generate a new sequential index.