# MultiIndex

In [1]:
import pandas as pd

## This Module's Dataset

In [8]:
bigmac = pd.read_csv("bigmac.csv", parse_dates=["Date"], date_format="%Y-%m-%d")
bigmac.head()

        Date      Country  Price in US Dollars
0 2000-04-01    Argentina             2.500000
1 2000-04-01    Australia             1.541667
2 2000-04-01       Brazil             1.648045
3 2000-04-01       Canada             1.938776
4 2000-04-01  Switzerland             3.470588

## Create a MultiIndex
- A `MultiIndex` is an index with multiple levels or layers.
- Pass the `set_index` method a list of column names to create a multi-index `DataFrame`.
- The order of the list's values will determine the order of the levels.
- Alternatively, we can pass the `read_csv` function's `index_col` parameter a list of columns.

In [9]:
bigmac.nunique()

Date                     33
Country                  57
Price in US Dollars    1350
dtype: int64

In [13]:
bigmac.set_index(keys=["Date", "Country"]).sort_index()

                                 Price in US Dollars
Date       Country
2000-04-01 Argentina                        2.500000
           Australia                        1.541667
           Brazil                           1.648045
           Britain                          3.002000
           Canada                           1.938776
...                                              ...
2020-07-01 Ukraine                          2.174714
           United Arab Emirates             4.015846
           United States                    5.710000
           Uruguay                          4.327418
           Vietnam                          2.847282

[1386 rows x 1 columns]

In [14]:
bigmac = pd.read_csv("bigmac.csv", parse_dates=["Date"], date_format="%Y-%m-%d", index_col=["Date", "Country"])
bigmac.head()

                        Price in US Dollars
Date       Country
2000-04-01 Argentina               2.500000
           Australia               1.541667
           Brazil                  1.648045
           Canada                  1.938776
           Switzerland             3.470588

## Extract and Rename Index Level Values
- The `get_level_values` method extracts an `Index` with the values from one level in the `MultiIndex`.
- Invoke the `get_level_values` on the `MultiIndex`, not the `DataFrame` itself.
- The method expects either the level's index position or its name.

In [ ]:
bigmac = pd.read_csv("bigmac.csv", parse_dates=["Date"], date_format="%Y-%m-%d", index_col=["Date", "Country"]).sort_index()
bigmac.head()

                        Price in US Dollars
Date       Country
2000-04-01 Argentina               2.500000
           Australia               1.541667
           Brazil                  1.648045
           Canada                  1.938776
           Switzerland             3.470588

In [17]:
bigmac.index.names

FrozenList(['Date', 'Country'])

In [21]:
bigmac.index.get_level_values("Date")
bigmac.index.get_level_values(0)
bigmac.index.get_level_values("Country")
bigmac.index.get_level_values(1)

Index(['Argentina', 'Australia', 'Brazil', 'Canada', 'Switzerland', 'Chile',
       'China', 'Czech Republic', 'Denmark', 'Euro area',
       ...
       'Singapore', 'Sweden', 'Thailand', 'Turkey', 'Taiwan', 'Ukraine',
       'Uruguay', 'United States', 'Vietnam', 'South Africa'],
      dtype='str', name='Country', length=1386)

- Invoke the `set_names` method on the `MultiIndex` to change one or more level names.
- Use the `names` and `level` parameter to target a nested index at a given level.
- Alternatively, pass `names` a list of strings to overwrite *all* level names.
- The `set_names` method returns a copy, so replace the original index to alter the `DataFrame`.

In [24]:
bigmac.index.set_names(names="Time", level=0)
bigmac.index.set_names(names="Time", level=1)
bigmac.index.set_names(names=["Time", "Location"])

MultiIndex([('2000-04-01',      'Argentina'),
            ('2000-04-01',      'Australia'),
            ('2000-04-01',         'Brazil'),
            ('2000-04-01',         'Canada'),
            ('2000-04-01',    'Switzerland'),
            ('2000-04-01',          'Chile'),
            ('2000-04-01',          'China'),
            ('2000-04-01', 'Czech Republic'),
            ('2000-04-01',        'Denmark'),
            ('2000-04-01',      'Euro area'),
            ...
            ('2020-07-01',      'Singapore'),
            ('2020-07-01',         'Sweden'),
            ('2020-07-01',       'Thailand'),
            ('2020-07-01',         'Turkey'),
            ('2020-07-01',         'Taiwan'),
            ('2020-07-01',        'Ukraine'),
            ('2020-07-01',        'Uruguay'),
            ('2020-07-01',  'United States'),
            ('2020-07-01',        'Vietnam'),
            ('2020-07-01',   'South Africa')],
           names=['Time', 'Location'], length=1386)

## Extract Rows from a MultiIndex DataFrame
- A `tuple` is an immutable list. It cannot be modified after creation.
- Create a tuple with a comma between elements. The Python community convention is to wrap the elements in parentheses.
- The `iloc` and `loc` accessors are available to extract rows by index position or label.
- For the `loc` accessor, pass a tuple to hold the labels from the index levels.

In [25]:
bigmac = pd.read_csv("bigmac.csv", parse_dates=["Date"], date_format="%Y-%m-%d", index_col=["Date", "Country"]).sort_index()
bigmac.head()

                      Price in US Dollars
Date       Country
2000-04-01 Argentina             2.500000
           Australia             1.541667
           Brazil                1.648045
           Britain               3.002000
           Canada                1.938776

In [31]:
bigmac.loc["2000-04-01"] 
bigmac.loc["2000-04-01", "Price in US Dollars"]
bigmac.loc["2000-04-01", "Canada"]
bigmac.loc[("2001-04-01", "Canada"), "Price in US Dollars"]

np.float64(2.134615385)

In [33]:
start = ("2000-04-01", "Hungary")
end = ("2000-04-01", "Poland")
bigmac.loc[start:end]

bigmac.loc[: ("2019-07-09", "Hungary"), "Price in US Dollars"]

Date        Country
2000-04-01  Argentina    2.500000
            Australia    1.541667
            Brazil       1.648045
            Britain      3.002000
            Canada       1.938776
                           ...
2019-07-09  Euro area    4.572252
            Guatemala    3.255124
            Honduras     3.512584
            Hong Kong    2.624672
            Hungary      3.097667
Name: Price in US Dollars, Length: 1238, dtype: float64

## The xs Method
- The `xs` (cross-section) method selects data at a particular level of a `MultiIndex`.
- Pass the `level` parameter the index name or position to target.
- By default, the matched level is dropped from the result. Pass `drop_level=False` to retain it.

In [34]:
bigmac = pd.read_csv("bigmac.csv", parse_dates=["Date"], date_format="%Y-%m-%d", index_col=["Date", "Country"]).sort_index()
bigmac.head()

                      Price in US Dollars
Date       Country
2000-04-01 Argentina             2.500000
           Australia             1.541667
           Brazil                1.648045
           Britain               3.002000
           Canada                1.938776

In [ ]:
bigmac.xs("2010-01-01", level="Date")

                Price in US Dollars
Country
Argentina                  1.842833
Australia                  3.977870
Brazil                     4.758313
Britain                    3.671328
Canada                     3.973765
Chile                      3.180282
China                      1.830912
Colombia                   3.912960
Costa Rica                 3.518890
Czech Republic             3.714432
Denmark                    5.993859
Egypt                      2.378774
Euro area                  4.843944
Hong Kong                  1.908065
Hungary                    3.857471
Indonesia                  2.242489
Israel                     3.991962
Japan                      3.495740
Malaysia                   2.081181
Mexico                     2.497317
New Zealand                3.611306
Norway                     7.023027
Pakistan                   2.421308
Peru                       2.806480
Philippines                2.210801
Poland                     2.856488
Russia                     2.339025
Saudi Arabia               2.666524
Singapore                  3.188707
South Africa               2.457389
South Korea                2.981149
Sri Lanka                  1.828313
Sweden                     5.506841
Switzerland                6.303642
Taiwan                     2.355343
Thailand                   2.112570
Turkey                     3.831677
UAE                        2.994827
Ukraine                    1.827676
United States              3.580000
Uruguay                    3.323263

In [42]:
bigmac.xs("Canada", level="Country")
bigmac.xs("Canada", level=1, drop_level=True)
bigmac.xs("Canada", level=1, drop_level=False)

                    Price in US Dollars
Date       Country
2000-04-01 Canada              1.938776
2001-04-01 Canada              2.134615
2002-04-01 Canada              2.121019
2003-04-01 Canada              2.206897
2004-05-01 Canada              2.328467
2005-06-01 Canada              2.625260
2006-01-01 Canada              3.007519
2006-05-01 Canada              3.141595
2007-01-01 Canada              3.089756
2007-06-01 Canada              3.683136
2008-06-01 Canada              4.075532
2009-07-01 Canada              3.350993
2010-01-01 Canada              3.973765
2010-07-01 Canada              4.000576
2011-07-01 Canada              5.000793
2012-01-01 Canada              4.632940
2012-07-01 Canada              5.022316
2013-01-01 Canada              5.394356
2013-07-01 Canada              5.260404
2014-01-01 Canada              5.013121
2014-07-01 Canada              5.251152
2015-01-01 Canada              4.639616
2015-07-01 Canada              4.535939
2016-01-01 Canada              4.144195
2016-07-01 Canada              4.604758
2017-01-01 Canada              4.509804
2017-07-01 Canada              4.655697
2018-01-01 Canada              5.257244
2018-07-01 Canada              5.067246
2019-01-01 Canada              5.084873
2019-07-09 Canada              5.155935
2020-01-14 Canada              5.181585
2020-07-01 Canada              5.076741

## The swaplevel Method
- The `swaplevel` method swaps two levels of a `MultiIndex`.
- Pass the two level identifiers by position or by name.

In [43]:
bigmac = pd.read_csv("bigmac.csv", parse_dates=["Date"], date_format="%Y-%m-%d", index_col=["Date", "Country"]).sort_index()
bigmac.head()

                      Price in US Dollars
Date       Country
2000-04-01 Argentina             2.500000
           Australia             1.541667
           Brazil                1.648045
           Britain               3.002000
           Canada                1.938776

In [46]:
bigmac.swaplevel(i="Country", j="Date")
bigmac.swaplevel(i="Country", j="Country")
bigmac.swaplevel(i=0, j=1)

                                 Price in US Dollars
Country              Date
Argentina            2000-04-01             2.500000
Australia            2000-04-01             1.541667
Brazil               2000-04-01             1.648045
Britain              2000-04-01             3.002000
Canada               2000-04-01             1.938776
...                                              ...
Ukraine              2020-07-01             2.174714
United Arab Emirates 2020-07-01             4.015846
United States        2020-07-01             5.710000
Uruguay              2020-07-01             4.327418
Vietnam              2020-07-01             2.847282

[1386 rows x 1 columns]

## The transpose Method
- The `transpose` method inverts/flips the horizontal and vertical axes of the `DataFrame`.

In [47]:
bigmac = pd.read_csv("bigmac.csv", parse_dates=["Date"], date_format="%Y-%m-%d", index_col=["Date", "Country"]).sort_index()
bigmac.head()

                      Price in US Dollars
Date       Country
2000-04-01 Argentina             2.500000
           Australia             1.541667
           Brazil                1.648045
           Britain               3.002000
           Canada                1.938776

In [48]:
bigmac.transpose()

Date                2000-04-01                                        \
Country              Argentina Australia    Brazil Britain    Canada
Price in US Dollars        2.5  1.541667  1.648045   3.002  1.938776

Date                                                                        \
Country                 Chile     China Czech Republic   Denmark Euro area
Price in US Dollars  2.451362  1.195652       1.390537  3.078358    2.3808

Date                 ... 2020-07-01                                            \
Country              ...     Sweden Switzerland    Taiwan  Thailand    Turkey
Price in US Dollars  ...   5.755931     6.90571  2.444282  4.078381  2.039507

Date                                                                        \
Country               Ukraine United Arab Emirates United States   Uruguay
Price in US Dollars  2.174714             4.015846          5.71  4.327418

Date
Country               Vietnam
Price in US Dollars  2.847282

[1 rows x 1386 columns]

In [50]:
start = ("2018-01-01", "China")
end = ("2018-01-01", "Denmark")

bigmac.loc[start: end].transpose()

Date                2018-01-01
Country                  China  Colombia Costa Rica Czech Republic  Denmark
Price in US Dollars   3.171642  3.832468   4.027932       3.807779  4.93202

## The stack Method
- The `stack` method moves one column index level to the row index.
- If the column axis only has 1 index, pandas will return a `MultiIndex` `Series`.
- Think of it like "stacking" index levels for a column `MultiIndex`.

In [54]:
world = pd.read_csv("worldstats.csv", index_col=["year", "country"]).sort_index()
world.head()

                   Population           GDP
year country
1960 Afghanistan    8994793.0  5.377778e+08
     Algeria       11124892.0  2.723638e+09
     Australia     10276477.0  1.856759e+10
     Austria        7047539.0  6.592694e+09
     Bahamas, The    109526.0  1.698023e+08

In [55]:
world.stack()

year  country
1960  Afghanistan  Population    8.994793e+06
                   GDP           5.377778e+08
      Algeria      Population    1.112489e+07
                   GDP           2.723638e+09
      Australia    Population    1.027648e+07
                                     ...
2015  World        GDP           7.343364e+13
      Zambia       Population    1.621177e+07
                   GDP           2.120156e+10
      Zimbabwe     Population    1.560275e+07
                   GDP           1.389294e+10
Length: 22422, dtype: float64

- The `to_frame` method converts a `Series` to a `DataFrame`.
- The `DataFrame` will have a 3-level `MultiIndex`.

## The unstack Method
- The `unstack` method moves a row index to the column index (the inverse of the `stack` method).
- By default, the `unstack` method will move the innermost index from rows to columns.
- The `columns` attribute provides the `MultiIndex` object.

In [63]:
world = pd.read_csv("worldstats.csv", index_col=["year", "country"]).sort_index().stack()

world.head()

year  country
1960  Afghanistan  Population    8.994793e+06
                   GDP           5.377778e+08
      Algeria      Population    1.112489e+07
                   GDP           2.723638e+09
      Australia    Population    1.027648e+07
dtype: float64

                           Population           GDP
year country
1960 Afghanistan         8.994793e+06  5.377778e+08
     Algeria             1.112489e+07  2.723638e+09
     Australia           1.027648e+07  1.856759e+10
     Austria             7.047539e+06  6.592694e+09
     Bahamas, The        1.095260e+05  1.698023e+08
...                               ...           ...
2015 Vietnam             9.170380e+07  1.935994e+11
     West Bank and Gaza  4.422143e+06  1.267740e+10
     World               7.346633e+09  7.343364e+13
     Zambia              1.621177e+07  2.120156e+10
     Zimbabwe            1.560275e+07  1.389294e+10

[11211 rows x 2 columns]

- We can customize the moved index with the `level` parameter.
- The `level` parameter accepts the level's index position or its name.
- We can also pass negative values to pull relative to the end. -3 means "third level from the end".

- The `level` parameter also accepts a list of positions/names.
- `[1,0]` moves the second level (`"country"`) first, then the first level (`"year"`).

- The `sort_index` method can sort the column index.
- Pass an `axis` argument of 1 or `"columns"`.

## The pivot Method
- The `pivot` method reshapes data from a tall format to a wide format.
- Ask yourself which direction the data will expand in if you add more entries.
- A tall/long format expands down. A wide format expands out.

In [67]:
sales = pd.read_csv("salesmen.csv")
sales.head()

       Date Salesman  Revenue
0  1/1/2025   Sharon     7172
1  1/2/2025   Sharon     6362
2  1/3/2025   Sharon     5982
3  1/4/2025   Sharon     7917
4  1/5/2025   Sharon     7837

In [68]:
sales["Salesman"].unique()

<StringArray>
['Sharon', 'Ronald', 'Dave', 'Alexander', 'Oscar']
Length: 5, dtype: str

- The `index` parameter sets the horizontal index of the pivoted `DataFrame`.
- The `columns` parameter sets the column whose values will be the columns in the pivoted `DataFrame`.
- The `values` parameter sets the values of the pivoted `DataFrame`.
- Pandas will populate the correct values based on the index and column intersections.

In [69]:
sales.pivot(index="Date", columns="Salesman", values="Revenue")

Salesman   Alexander  Dave  Oscar  Ronald  Sharon
Date
1/1/2025        4430  1864   5250    2639    7172
1/10/2025        301  7105   7663    8267    7543
1/11/2025       9489  6851   8888    1340    1053
1/12/2025       8719  7147   3092     279    4362
1/13/2025       2349  6160   6139    7540    6812
...              ...   ...    ...     ...     ...
9/5/2025        2439   211   7743    4252     992
9/6/2025        7585  7293   5072    1112     556
9/7/2025        6669  9774   5230    3608    6499
9/8/2025        3058  8194   7755    5762    9621
9/9/2025        6823  4733   5684    8922    1231

[365 rows x 5 columns]

## The melt Method
- The `melt` method is the inverse of the `pivot` method.
- It converts a 'wide' dataset into a 'tall' dataset.
- The `melt` method is ideal when you have multiple columns storing the *same* data point.
- Ask yourself whether the column's values are a *type* of the column header. If they're not, the data is likely stored in a wide format.

In [71]:
quarters = pd.read_csv("quarters.csv")

quarters.head()

  Salesman      Q1      Q2      Q3      Q4
0    Boris  602908  233879  354479   32704
1    Piers   43790  514863  297151  544493
2    Tommy  392668  113579  430882  247231
3   Travis  834663  266785  749238  570524
4    Cindy  580935  411379  110390  651572

- The `id_vars` parameter accepts the column whose values will be repeated for every column.
- The `var_name` parameter sets the name of the new column for the varying values (the former column names).
- The `value_name` parameter sets the new name of the values column (holding the values from the original `DataFrame`).

In [76]:
quarters.melt(id_vars="Salesman", value_vars=["Q1", "Q2", "Q3", "Q4"], var_name="Quarter", value_name="Revenue")

     Salesman Quarter  Revenue
0       Boris      Q1   602908
1       Piers      Q1    43790
2       Tommy      Q1   392668
3      Travis      Q1   834663
4       Cindy      Q1   580935
5         Rob      Q1   656644
6        Mike      Q1   486141
7       Stacy      Q1   479662
8   Alexandra      Q1   992673
9       Boris      Q2   233879
10      Piers      Q2   514863
11      Tommy      Q2   113579
12     Travis      Q2   266785
13      Cindy      Q2   411379
14        Rob      Q2    70803
15       Mike      Q2   600753
16      Stacy      Q2   742806
17  Alexandra      Q2   879183
18      Boris      Q3   354479
19      Piers      Q3   297151
20      Tommy      Q3   430882
21     Travis      Q3   749238
22      Cindy      Q3   110390
23        Rob      Q3   375948
24       Mike      Q3   742716
25      Stacy      Q3   770712
26  Alexandra      Q3    37945
27      Boris      Q4    32704
28      Piers      Q4   544493
29      Tommy      Q4   247231
30     Travis      Q4   570524
31      Cindy      Q4   651572
32        Rob      Q4   321388
33       Mike      Q4   404995
34      Stacy      Q4     2501
35  Alexandra      Q4   293710

## The pivot_table Method
- A pivot table is a `DataFrame` whose values are aggregations of groups of values from another table.
- The `pivot_table` method operates similarly to the Pivot Table feature in Excel.

In [79]:
foods = pd.read_csv("foods.csv")
foods.head()

  First Name  Gender          City Frequency       Item  Spend
0      Wanda  Female      Stamford    Weekly     Burger  15.66
1       Eric    Male      Stamford     Daily    Chalupa  10.56
2    Charles    Male      New York     Never      Sushi  42.14
3       Anna  Female  Philadelphia      Once  Ice Cream  11.01
4    Deborah  Female  Philadelphia     Daily    Chalupa  23.49

- The `values` parameter accepts the numeric column whose values will be aggregated.
- The `index` parameter sets the index labels of the pivot table. A `MultiIndex` is permitted.
- The `aggfunc` parameter declares the aggregation function.
- The default aggregation is mean/average.

In [80]:
foods.pivot_table(values="Spend", index="Gender", aggfunc="mean")

            Spend
Gender
Female  50.709629
Male    49.397623

In [81]:
foods[foods["Gender"] == "Female"]["Spend"].mean()

np.float64(50.70962890625)

- The `sum` aggregation adds the values together.
- The next example finds the spend by item.

- The `index` parameter accepts a list of columns.
- The pivot table will have a `MultiIndex`.

In [82]:
foods.pivot_table(values="Spend", index="Item", aggfunc="sum")

             Spend
Item
Burger     7765.73
Burrito    8270.44
Chalupa    7644.52
Donut      8758.76
Ice Cream  8886.99
Sushi      8742.93

- The `columns` parameter sets the column labels of the pivot table. A `MultiIndex` is permitted.

In [83]:
foods.pivot_table(values="Spend", index=["Gender", "Item"], aggfunc="sum")

                    Spend
Gender Item
Female Burger     4094.30
       Burrito    4257.82
       Chalupa    4152.26
       Donut      4743.00
       Ice Cream  4032.87
       Sushi      4683.08
Male   Burger     3671.43
       Burrito    4012.62
       Chalupa    3492.26
       Donut      4015.76
       Ice Cream  4854.12
       Sushi      4059.85

- Other aggregation functions (`count`, `max` and `min`) are also availble.

- The `margins` parameter adds an `All` row/column with subtotals.