# The GroupBy Object

In [2]:
import pandas as pd

## The Fortune 1000 Dataset
- The **Fortune 1000** is a listing of the 1000 largest American companies as ranked by Fortune magazine.
- The `DataFrame` includes the company's name, sector, industry, and revenues, profits, and employees.

In [ ]:
fortune = pd.read_csv("fortune1000.csv", index_col="Rank")
sectors = fortune.groupby("Sector")
fortune.head()

,Company,Sector,Industry,Revenue,Profits,Employees
Rank,,,,,,
1,Walmart,Retailing,General Merchandisers,482130,14694,2300000
2,Exxon Mobil,Energy,Petroleum Refining,246204,16150,75600
3,Apple,Technology,"Computers, Office Equipment",233715,53394,110000
4,Berkshire Hathaway,Financials,Insurance: Property and Casualty (Stock),210821,24083,331000
5,McKesson,Health Care,Wholesalers: Health Care,181241,1476,70400

## The groupby Method
- **Grouping** is a way to organize/categorize/group the data based on a column's values.
- The `groupby` method returns a `DataFrameGroupBy` object.
- The `DataFrameGroupBy` object represents a group/collection of `DataFrame` objects in a dictionary-like structure.
- The `DataFrameGroupBy` object can perform aggregate operations on *each* group within it.

In [6]:
sectors = fortune.groupby("Sector")
sectors

In [7]:
len(sectors)

21

In [8]:
fortune["Sector"].nunique()

21

In [10]:
sectors.size()

Sector
Aerospace & Defense              20
Apparel                          15
Business Services                51
Chemicals                        30
Energy                          122
Engineering & Construction       26
Financials                      139
Food and Drug Stores             15
Food, Beverages & Tobacco        43
Health Care                      75
Hotels, Resturants & Leisure     25
Household Products               28
Industrials                      46
Materials                        43
Media                            25
Motor Vehicles & Parts           24
Retailing                        80
Technology                      102
Telecommunications               15
Transportation                   36
Wholesalers                      40
dtype: int64

## Retrieve Groups and Rows
- The `get_group` method on the `DataFrameGroupBy` object retrieves a nested `DataFrame` belonging to a specific group/category.

In [11]:
fortune = pd.read_csv("fortune1000.csv", index_col="Rank")
sectors = fortune.groupby("Sector")
fortune.head()

,Company,Sector,Industry,Revenue,Profits,Employees
Rank,,,,,,
1,Walmart,Retailing,General Merchandisers,482130,14694,2300000
2,Exxon Mobil,Energy,Petroleum Refining,246204,16150,75600
3,Apple,Technology,"Computers, Office Equipment",233715,53394,110000
4,Berkshire Hathaway,Financials,Insurance: Property and Casualty (Stock),210821,24083,331000
5,McKesson,Health Care,Wholesalers: Health Care,181241,1476,70400

In [12]:
sectors

In [14]:
sectors.get_group("Energy")
sectors.get_group("Technology")

,Company,Sector,Industry,Revenue,Profits,Employees
Rank,,,,,,
3,Apple,Technology,"Computers, Office Equipment",233715,53394,110000
18,Amazon.com,Technology,Internet Services and Retailing,107006,596,230800
20,HP,Technology,"Computers, Office Equipment",103355,4554,287000
25,Microsoft,Technology,Computer Software,93580,12193,118000
31,IBM,Technology,Information Technology Services,82461,13190,411798
...,...,...,...,...,...,...
970,Rackspace Hosting,Technology,Internet Services and Retailing,2001,126,6189
971,VeriFone Systems,Technology,"Computers, Office Equipment",2001,79,5400
975,Super Micro Computer,Technology,"Computers, Office Equipment",1991,102,2285
984,Nuance Communications,Technology,Computer Software,1931,-115,13500
990,F5 Networks,Technology,Network and Other Communications Equipment,1920,365,4178

In [15]:
fortune.head()

,Company,Sector,Industry,Revenue,Profits,Employees
Rank,,,,,,
1,Walmart,Retailing,General Merchandisers,482130,14694,2300000
2,Exxon Mobil,Energy,Petroleum Refining,246204,16150,75600
3,Apple,Technology,"Computers, Office Equipment",233715,53394,110000
4,Berkshire Hathaway,Financials,Insurance: Property and Casualty (Stock),210821,24083,331000
5,McKesson,Health Care,Wholesalers: Health Care,181241,1476,70400

In [16]:
sectors.first()

,Company,Industry,Revenue,Profits,Employees
Sector,,,,,
Aerospace & Defense,Boeing,Aerospace and Defense,96114,5176,161400
Apparel,Nike,Apparel,30601,3273,62600
Business Services,ManpowerGroup,Temporary Help,19330,419,27000
Chemicals,Dow Chemical,Chemicals,48778,7685,49495
Energy,Exxon Mobil,Petroleum Refining,246204,16150,75600
Engineering & Construction,Fluor,"Engineering, Construction",18114,413,38758
Financials,Berkshire Hathaway,Insurance: Property and Casualty (Stock),210821,24083,331000
Food and Drug Stores,CVS Health,Food and Drug Stores,153290,5237,199000
"Food, Beverages & Tobacco",Archer Daniels Midland,Food Production,67702,1849,32300
Health Care,McKesson,Wholesalers: Health Care,181241,1476,70400
"Hotels, Resturants & Leisure",McDonald’s,Food Services,25413,4529,420000
Household Products,Procter & Gamble,Household and Personal Products,78756,7036,110000
Industrials,General Electric,Industrial Machinery,140389,-6126,333000
Materials,Alcoa,Metals,22534,-322,60000
Media,Disney,Entertainment,52465,8382,185000
Motor Vehicles & Parts,General Motors,Motor Vehicles and Parts,152356,9687,215000
Retailing,Walmart,General Merchandisers,482130,14694,2300000
Technology,Apple,"Computers, Office Equipment",233715,53394,110000
Telecommunications,AT&T,Telecommunications,146801,13345,281450
Transportation,UPS,"Mail, Package, and Freight Delivery",58363,4844,341240
Wholesalers,Sysco,Wholesalers: Food and Grocery,48681,687,51700

## Methods on the GroupBy Object
- Use square brackets on the `DataFrameGroupBy` object to extract a column from the original `DataFrame`.
- The resulting `SeriesGroupBy` object will have aggregation methods available on it.
- Pandas will perform the calculation on *every* group within the collection.
- For example, the `sum` method will sum together the revenues for every row by group/category.

In [17]:
fortune = pd.read_csv("fortune1000.csv", index_col="Rank")
sectors = fortune.groupby("Sector")
fortune.head()

,Company,Sector,Industry,Revenue,Profits,Employees
Rank,,,,,,
1,Walmart,Retailing,General Merchandisers,482130,14694,2300000
2,Exxon Mobil,Energy,Petroleum Refining,246204,16150,75600
3,Apple,Technology,"Computers, Office Equipment",233715,53394,110000
4,Berkshire Hathaway,Financials,Insurance: Property and Casualty (Stock),210821,24083,331000
5,McKesson,Health Care,Wholesalers: Health Care,181241,1476,70400

In [24]:
sectors["Revenue"].sum()
sectors["Employees"].sum()
sectors["Profits"].max()
sectors["Profits"].min()
sectors["Profits"].mean()

Sector
Aerospace & Defense             1437.100000
Apparel                          549.066667
Business Services                553.470588
Chemicals                        754.266667
Energy                          -602.024590
Engineering & Construction       204.000000
Financials                      1872.007194
Food and Drug Stores            1117.266667
Food, Beverages & Tobacco       1195.744186
Health Care                     1414.853333
Hotels, Resturants & Leisure     827.880000
Household Products               515.285714
Industrials                      451.391304
Materials                        102.976744
Media                            973.880000
Motor Vehicles & Parts          1079.083333
Retailing                        597.875000
Technology                      1769.343137
Telecommunications              3242.466667
Transportation                  1226.916667
Wholesalers                      205.825000
Name: Profits, dtype: float64

- Pass a list to target multiple columns.

In [26]:
sectors[["Revenue", "Profits"]].sum()
sectors[["Revenue", "Profits"]].mean()

                                   Revenue      Profits
Sector
Aerospace & Defense           17897.000000  1437.100000
Apparel                        6397.866667   549.066667
Business Services              5337.156863   553.470588
Chemicals                      8129.900000   754.266667
Energy                        12441.057377  -602.024590
Engineering & Construction     5922.423077   204.000000
Financials                    15950.784173  1872.007194
Food and Drug Stores          32251.266667  1117.266667
Food, Beverages & Tobacco     12929.465116  1195.744186
Health Care                   21529.426667  1414.853333
Hotels, Resturants & Leisure   6781.840000   827.880000
Household Products             8383.464286   515.285714
Industrials                   10816.978261   451.391304
Materials                      6026.627907   102.976744
Media                          8830.560000   973.880000
Motor Vehicles & Parts        20105.833333  1079.083333
Retailing                     18313.450000   597.875000
Technology                    13505.882353  1769.343137
Telecommunications            30788.933333  3242.466667
Transportation                11347.444444  1226.916667
Wholesalers                   11120.000000   205.825000

## The agg Method
- The `agg` method applies different aggregation methods on different columns.
- Invoke the `agg` method directly on the `DataFrameGroupBy` object.
- Pass the method a dictionary where the keys are the columns and the values are the aggregation operations.

In [27]:
fortune = pd.read_csv("fortune1000.csv", index_col="Rank")
sectors = fortune.groupby("Sector")
fortune.head()

,Company,Sector,Industry,Revenue,Profits,Employees
Rank,,,,,,
1,Walmart,Retailing,General Merchandisers,482130,14694,2300000
2,Exxon Mobil,Energy,Petroleum Refining,246204,16150,75600
3,Apple,Technology,"Computers, Office Equipment",233715,53394,110000
4,Berkshire Hathaway,Financials,Insurance: Property and Casualty (Stock),210821,24083,331000
5,McKesson,Health Care,Wholesalers: Health Care,181241,1476,70400

In [30]:
sectors.agg({"Revenue": "sum", "Profits": "max", "Employees": "mean"})

                              Revenue  Profits     Employees
Sector
Aerospace & Defense            357940     7608  48402.850000
Apparel                         95968     3273  23093.133333
Business Services              272195     6328  26687.254902
Chemicals                      243897     7685  15455.033333
Energy                        1517809    16150   9745.303279
Engineering & Construction     153983      803  15642.615385
Financials                    2217159    24442  24172.287770
Food and Drug Stores           483769     5237  93026.533333
Food, Beverages & Tobacco      555967     7351  28177.488372
Health Care                   1614707    18108  35710.520000
Hotels, Resturants & Leisure   169546     5920  99369.800000
Household Products             234737     7036  23072.785714
Industrials                    497581     4833  33591.934783
Materials                      259145      991  14840.069767
Media                          220764     8382  22012.560000
Motor Vehicles & Parts         482540     9687  45106.666667
Retailing                     1465076    14694  77845.362500
Technology                    1377600    53394  35087.735294
Telecommunications             461834    17879  55497.866667
Transportation                 408508     7610  42688.694444
Wholesalers                    444800     1472  13139.925000

- Pass a list of operations to compute multiple statistics on the same column at once.

## Grouping by Multiple Columns
- Pass a list of columns to the `groupby` method to group by pairings of values across columns.
- Target a column to retrieve the `SeriesGroupBy` object, then perform an aggregation with a method.
- Pandas will return a `MultiIndex` `Series` where the levels will be the original groups.

In [32]:
fortune = pd.read_csv("fortune1000.csv", index_col="Rank")
sectors = fortune.groupby(["Sector", "Industry"])
fortune.head()

,Company,Sector,Industry,Revenue,Profits,Employees
Rank,,,,,,
1,Walmart,Retailing,General Merchandisers,482130,14694,2300000
2,Exxon Mobil,Energy,Petroleum Refining,246204,16150,75600
3,Apple,Technology,"Computers, Office Equipment",233715,53394,110000
4,Berkshire Hathaway,Financials,Insurance: Property and Casualty (Stock),210821,24083,331000
5,McKesson,Health Care,Wholesalers: Health Care,181241,1476,70400

In [33]:
sectors.size()

Sector               Industry
Aerospace & Defense  Aerospace and Defense                            20
Apparel              Apparel                                          15
Business Services    Advertising, marketing                            2
                     Diversified Outsourcing Services                 14
                     Education                                         3
                                                                      ..
Transportation       Trucking, Truck Leasing                           9
Wholesalers          Miscellaneous                                     1
                     Wholesalers: Diversified                         25
                     Wholesalers: Electronics and Office Equipment     8
                     Wholesalers: Food and Grocery                     6
Length: 79, dtype: int64

In [35]:
sectors["Revenue"].sum()
sectors["Employees"].mean()

Sector               Industry
Aerospace & Defense  Aerospace and Defense                            48402.850000
Apparel              Apparel                                          23093.133333
Business Services    Advertising, marketing                           62050.000000
                     Diversified Outsourcing Services                 50595.000000
                     Education                                        15585.000000
                                                                          ...
Transportation       Trucking, Truck Leasing                          18939.555556
Wholesalers          Miscellaneous                                     9200.000000
                     Wholesalers: Diversified                          9353.240000
                     Wholesalers: Electronics and Office Equipment    20832.625000
                     Wholesalers: Food and Grocery                    19317.500000
Name: Employees, Length: 79, dtype: float64

## Iterating over Groups
- We can iterate over every `DataFrame` in a `DataFrameGroupBy` with a `for` loop.
- Each iteration yields a tuple of `(group_name, group_DataFrame)`.

- The `DataFrameGroupBy` object supports the `apply` method (just like a `Series` and a `DataFrame` do).
- The `apply` method invokes a function on every nested `DataFrame` in the `DataFrameGroupBy` object.
- It captures the return values of the functions and collects them in a new `DataFrame` (the return value).