# Working with Dates and Times

In [1]:
import pandas as pd

## Review of Python's datetime Module
- A module is a file of Python code.
- The `datetime` module is part of Python's standard library, a collection of built-in features.
- The common alias for the `datetime` module is `dt`.

In [2]:
import datetime as dt

- The `datetime` module exports `date`, `time`, and `datetime` classes for representing dates and datetimes.
- The `date` constructor accepts arguments for year, month, and day.
- The `time` constructor accepts arguments for hours, minutes, and seconds.
- The `datetime` constructor accepts arguments for year, month, day, hour, minute, and second.
- The constructors default to 0 for any missing values.

In [3]:
someday = dt.date(2026, 12, 15)
type(someday)

datetime.date

In [4]:
someday.year
someday.month
someday.day

15

In [5]:
sometime = dt.time(8, 30, 45)

In [6]:
sometime.hour

8

In [7]:
dt.datetime(2026, 12, 15)
sometime = dt.datetime(2026, 12, 15, 8, 13, 59)
type(sometime)

datetime.datetime

In [8]:
sometime.year

2026

## The dt Attribute
- The `dt` attribute on a `Series` exposes a `DatetimeProperties` object with attributes/methods for working with datetimes.
- The `DatetimeProperties` object has attributes like `day`, `month`, and `year` to reveal information about each date in the `Series`.

In [9]:
stocks = pd.read_csv("ibm.csv", parse_dates=["Date"])
stocks.head()

        Date  Open  High   Low  Close  Volume
0 1962-01-02  1.48  1.48  1.46   1.46  407940
1 1962-01-03  1.46  1.48  1.46   1.48  305955
2 1962-01-04  1.48  1.48  1.46   1.46  274575
3 1962-01-05  1.46  1.46  1.43   1.43  384405
4 1962-01-08  1.43  1.43  1.39   1.41  572685

In [10]:
stocks["Date"].dt

In [11]:
stocks["Date"].dt.day
stocks["Date"].dt.month

0        1
1        1
2        1
3        1
4        1
        ..
16123    1
16124    1
16125    1
16126    1
16127    1
Name: Date, Length: 16128, dtype: int32

- The `day_name` method returns the written day of the week.

- Attributes like `is_month_end` and `is_quarter_start` return Boolean `Series`.

## The Timestamp Type
- Pandas has its own `Timestamp` type for modelling a date or datetime.

In [12]:
stocks = pd.read_csv("ibm.csv", parse_dates=["Date"])
stocks.head()

        Date  Open  High   Low  Close  Volume
0 1962-01-02  1.48  1.48  1.46   1.46  407940
1 1962-01-03  1.46  1.48  1.46   1.48  305955
2 1962-01-04  1.48  1.48  1.46   1.46  274575
3 1962-01-05  1.46  1.46  1.43   1.43  384405
4 1962-01-08  1.43  1.43  1.39   1.41  572685

In [13]:
timestamp = pd.Timestamp(2026, 12, 15, 8, 30, 5)
timestamp.year

2026

- The `Timestamp` constructor also accepts `dt.date` and `dt.datetime` objects.
- The `Timestamp` cannot model a time without a day and thus does not accept `dt.time` objects.

In [14]:
pd.Timestamp(dt.date(2026, 12, 15))

Timestamp('2026-12-15 00:00:00')

- When we convert a column to `datetime64`, each row actually stores a `Timestamp`.

## Extracting Datetime Rows from a DataFrame
- When generating a Boolean `Series` against a `datetime64` column, you can use either strings, `datetime` objects, or `Timestamp` objects.

In [15]:
stocks = pd.read_csv("ibm.csv", parse_dates=["Date"]).sort_values("Date")
stocks.head()

        Date  Open  High   Low  Close  Volume
0 1962-01-02  1.48  1.48  1.46   1.46  407940
1 1962-01-03  1.46  1.48  1.46   1.48  305955
2 1962-01-04  1.48  1.48  1.46   1.46  274575
3 1962-01-05  1.46  1.46  1.43   1.43  384405
4 1962-01-08  1.43  1.43  1.39   1.41  572685

In [16]:
stocks[stocks["Date"] == "1995-04-03"]

stocks[stocks["Date"].between("1995-04-03", "1995-04-11")]

           Date   Open   High    Low  Close    Volume
8369 1995-04-03   9.79   9.93   9.79   9.86   7924914
8370 1995-04-04   9.89   9.95   9.82   9.87   7048366
8371 1995-04-05   9.86  10.01   9.86   9.99   8402727
8372 1995-04-06  10.04  10.07   9.95   9.98   6219516
8373 1995-04-07   9.96  10.13   9.93   9.99  10160007
8374 1995-04-10   9.99  10.23   9.99  10.23   8851670
8375 1995-04-11  10.22  10.34  10.19  10.32  10798904

- We can set a column of `datetime` values as the index.
- The `DataFrame` sill store a `DatetimeIndex` object.

In [17]:
stocks = pd.read_csv("ibm.csv", parse_dates=["Date"], index_col="Date").sort_index()
stocks.tail()

              Open    High     Low   Close    Volume
Date
2026-01-26  293.16  296.82  293.14  296.33   3726900
2026-01-27  297.16  297.33  293.27  293.86   2954900
2026-01-28  294.17  295.95  291.26  294.16   5790300
2026-01-29  317.86  319.90  303.47  309.24  10124900
2026-01-30  307.60  307.78  299.73  306.70   5938900

In [18]:
stocks.index[0]

Timestamp('1962-01-02 00:00:00')

- Use the `iloc` accessor for index position-based extraction.

In [19]:
stocks.iloc[5]

Open           1.41
High           1.44
Low            1.41
Close          1.42
Volume    517770.00
Name: 1962-01-09 00:00:00, dtype: float64

- Use the `loc` accessor for index label-based extraction.
- The accessor accepts strings, `datetime` objects, or `Timestamp` objects.
- Use list slicing to extract a sequence of dates.
- The `truncate` method is another alternative for extracting a range of dates..

In [20]:
stocks.loc["2022-03-04"]

Open          107.51
High          110.06
Low           107.35
Close         109.43
Volume    4402400.00
Name: 2022-03-04 00:00:00, dtype: float64

- The second argument to `loc` represents the column(s) to target.

In [21]:
stocks.truncate("2022-03-04", "2023-01-01")

              Open    High     Low   Close   Volume
Date
2022-03-04  107.51  110.06  107.35  109.43  4402400
2022-03-07  109.30  110.54  108.56  108.95  5047400
2022-03-08  109.43  110.92  107.87  108.62  4887600
2022-03-09  110.11  110.71  108.81  109.08  4403500
2022-03-10  108.68  108.92  106.41  107.47  5326800
...            ...     ...     ...     ...      ...
2022-12-23  126.01  127.15  125.12  126.96  2092500
2022-12-27  127.03  127.92  126.58  127.65  2742400
2022-12-28  127.63  128.00  125.44  125.50  2539500
2022-12-29  126.00  127.51  125.88  126.43  2337200
2022-12-30  125.96  126.29  124.99  126.28  2858000

[209 rows x 5 columns]

- Pass a shorter string like `"2025"` or `"2025-03"` to `loc` to select all rows within that year or month.

## The DateOffset Object
- A `DateOffset` object adds time to a `Timestamp` to arrive at a new `Timestamp`.
- The `DateOffset` constructor accepts `days`, `weeks`, `months`, `years` parameters, and more.
- We can pass a `DateOffset` object to the `freq` parameter of the `pd.date_range` function.

In [24]:
stocks = pd.read_csv("ibm.csv", parse_dates=["Date"], index_col="Date").sort_index()
stocks.head()

            Open  High   Low  Close  Volume
Date
1962-01-02  1.48  1.48  1.46   1.46  407940
1962-01-03  1.46  1.48  1.46   1.48  305955
1962-01-04  1.48  1.48  1.46   1.46  274575
1962-01-05  1.46  1.46  1.43   1.43  384405
1962-01-08  1.43  1.43  1.39   1.41  572685

In [ ]:
pd.Timestamp(2026, 2, 3) + pd.DateOffset(days=5)
pd.Timestamp(2026, 2, 3) - pd.DateOffset(days=5)
pd.Timestamp(2026, 2, 3) - pd.DateOffset(weeks=5, days=3)

stocks.index + pd.DateOffset(days=5)
stocks.index + pd.DateOffset(months=3)
stocks.index + pd.DateOffset(years=1)

DatetimeIndex(['1963-01-02', '1963-01-03', '1963-01-04', '1963-01-05',
               '1963-01-08', '1963-01-09', '1963-01-10', '1963-01-11',
               '1963-01-12', '1963-01-15',
               ...
               '2027-01-16', '2027-01-20', '2027-01-21', '2027-01-22',
               '2027-01-23', '2027-01-26', '2027-01-27', '2027-01-28',
               '2027-01-29', '2027-01-30'],
              dtype='datetime64[us]', name='Date', length=16128, freq=None)

## The date_range Function
- The `pd.date_range` function generates a `MultiIndex` of values from a start point to an endpoint.
- We can customize the frequency/gap between each `Timestamp` with the `freq` parameter.
- We can also ask it to generate a certain number of values with the `periods` parameter and either a start or end.

In [34]:
stocks = pd.read_csv("ibm.csv", parse_dates=["Date"], index_col="Date").sort_index()
stocks.head()

            Open  High   Low  Close  Volume
Date
1962-01-02  1.48  1.48  1.46   1.46  407940
1962-01-03  1.46  1.48  1.46   1.48  305955
1962-01-04  1.48  1.48  1.46   1.46  274575
1962-01-05  1.46  1.46  1.43   1.43  384405
1962-01-08  1.43  1.43  1.39   1.41  572685

In [38]:
pd.date_range(start="1991-04-12", end="2026-04-12", freq="1h")
pd.date_range(start="1991-04-12", end="2026-04-12", freq="7D")
pd.date_range(start="1991-04-12", freq="7D", periods=200)

DatetimeIndex(['1991-04-12', '1991-04-19', '1991-04-26', '1991-05-03',
               '1991-05-10', '1991-05-17', '1991-05-24', '1991-05-31',
               '1991-06-07', '1991-06-14',
               ...
               '1994-12-02', '1994-12-09', '1994-12-16', '1994-12-23',
               '1994-12-30', '1995-01-06', '1995-01-13', '1995-01-20',
               '1995-01-27', '1995-02-03'],
              dtype='datetime64[us]', length=200, freq='7D')

- Let's extract all of the rows that fell on a given date each year.

## Specialized Date Offsets
- Pandas nests more specialized date offsets in `pd.tseries.offsets`.
- The offsets represent custom spans of time (month end, quarter end, year begin, etc).
- Use `+` to move time forward into the future.
- Use `-` to move time backward into the past.

In [40]:
stocks = pd.read_csv("ibm.csv", parse_dates=["Date"], index_col="Date").sort_index()
stocks.head()

            Open  High   Low  Close  Volume
Date
1962-01-02  1.48  1.48  1.46   1.46  407940
1962-01-03  1.46  1.48  1.46   1.48  305955
1962-01-04  1.48  1.48  1.46   1.46  274575
1962-01-05  1.46  1.46  1.43   1.43  384405
1962-01-08  1.43  1.43  1.39   1.41  572685

In [44]:
stocks.index + pd.tseries.offsets.MonthEnd()
stocks.index - pd.tseries.offsets.MonthEnd()

stocks.index + pd.tseries.offsets.QuarterEnd()

DatetimeIndex(['1962-03-31', '1962-03-31', '1962-03-31', '1962-03-31',
               '1962-03-31', '1962-03-31', '1962-03-31', '1962-03-31',
               '1962-03-31', '1962-03-31',
               ...
               '2026-03-31', '2026-03-31', '2026-03-31', '2026-03-31',
               '2026-03-31', '2026-03-31', '2026-03-31', '2026-03-31',
               '2026-03-31', '2026-03-31'],
              dtype='datetime64[us]', name='Date', length=16128, freq=None)

## Timedeltas
- A `Timedelta` is a pandas object that represents a duration (an amount of time).
- Subtracting two `Timestamp` objects will yield a `Timedelta` object (this applies to subtracting a `Series` from another `Series`).
- The `Timedelta` constructor accepts parameters for time as well as string descriptions.

In [48]:
pd.Timestamp("2026-03-31 12:30:48") - pd.Timestamp("2026-03-20 19:25:59")

pd.Timedelta(days=3, hours=2, minutes=5)
pd.Timedelta("3 days 2 hours 5 minutes")

Timedelta('3 days 02:05:00')

In [55]:
ecommerce = pd.read_csv("ecommerce.csv", index_col="ID", parse_dates=["order_date", "delivery_date"], date_format="%m/%d/%y")

ecommerce.head()

   order_date delivery_date
ID
1  1998-05-24    1999-02-05
2  1992-04-22    1998-03-06
4  1991-02-10    1992-08-26
5  1992-07-21    1997-11-20
7  1993-09-02    1998-06-10

In [58]:
ecommerce["delivery_time"] = ecommerce["delivery_date"] - ecommerce["order_date"]
ecommerce.head()

   order_date delivery_date delivery_time
ID
1  1998-05-24    1999-02-05      257 days
2  1992-04-22    1998-03-06     2144 days
4  1991-02-10    1992-08-26      563 days
5  1992-07-21    1997-11-20     1948 days
7  1993-09-02    1998-06-10     1742 days

In [59]:
ecommerce["delivery_date"] + ecommerce["delivery_time"]

ID
1     1999-10-20
2     2004-01-18
4     1994-03-12
5     2003-03-22
7     2003-03-18
         ...
990   2000-09-12
991   2004-10-18
993   2005-10-06
994   1993-06-23
997   1993-07-01
Length: 501, dtype: datetime64[us]